import {AnalyticsData, Order, Part, Sale, ScanRecord, ServiceTicket} from '../types';

export const mockParts: Part[] = [
  // Power Systems (A section)
  {
    id: 'P001',
    name: 'Battery Pack',
    sku: 'BAT-5000',
    quantity: 45,
    category: 'Power',
    price: 8500,
    location: 'A-01',
  },
  {
    id: 'P002',
    name: 'Battery Cell',
    sku: 'BAT-1000',
    quantity: 320,
    category: 'Power',
    price: 150,
    location: 'A-02',
  },
  {
    id: 'P003',
    name: 'Power Inverter',
    sku: 'INV-2000',
    quantity: 89,
    category: 'Power',
    price: 1200,
    location: 'A-03',
  },
  {
    id: 'P004',
    name: 'Charging Controller',
    sku: 'CHG-CTRL',
    quantity: 67,
    category: 'Power',
    price: 800,
    location: 'A-04',
  },
  {
    id: 'P005',
    name: 'High Voltage Cable',
    sku: 'HV-CABLE',
    quantity: 156,
    category: 'Power',
    price: 250,
    location: 'A-05',
  },
  {
    id: 'P006',
    name: 'Battery Management System',
    sku: 'BMS-100',
    quantity: 78,
    category: 'Power',
    price: 2200,
    location: 'A-06',
  },
  {
    id: 'P007',
    name: 'DC-DC Converter',
    sku: 'DCDC-500',
    quantity: 134,
    category: 'Power',
    price: 450,
    location: 'A-07',
  },
  {
    id: 'P008',
    name: 'Fuse Box',
    sku: 'FUSE-BOX',
    quantity: 92,
    category: 'Power',
    price: 180,
    location: 'A-08',
  },
  {
    id: 'P009',
    name: 'Grounding Strap',
    sku: 'GRND-STRP',
    quantity: 245,
    category: 'Power',
    price: 25,
    location: 'A-09',
  },
  {
    id: 'P010',
    name: 'Insulation Tape',
    sku: 'INS-TAPE',
    quantity: 180,
    category: 'Power',
    price: 12,
    location: 'A-10',
  },

  // Drivetrain (B section)
  {
    id: 'P011',
    name: 'Electric Motor',
    sku: 'MOT-3000',
    quantity: 23,
    category: 'Drivetrain',
    price: 12000,
    location: 'B-01',
  },
  {
    id: 'P012',
    name: 'Motor Controller',
    sku: 'MOT-CTRL',
    quantity: 45,
    category: 'Drivetrain',
    price: 2800,
    location: 'B-02',
  },
  {
    id: 'P013',
    name: 'Gearbox Assembly',
    sku: 'GEAR-100',
    quantity: 34,
    category: 'Drivetrain',
    price: 4500,
    location: 'B-03',
  },
  {
    id: 'P014',
    name: 'Drive Shaft',
    sku: 'DRIVE-SHAFT',
    quantity: 67,
    category: 'Drivetrain',
    price: 890,
    location: 'B-04',
  },
  {
    id: 'P015',
    name: 'CV Joint',
    sku: 'CV-JOINT',
    quantity: 123,
    category: 'Drivetrain',
    price: 340,
    location: 'B-05',
  },
  {
    id: 'P016',
    name: 'Differential Unit',
    sku: 'DIFF-200',
    quantity: 28,
    category: 'Drivetrain',
    price: 3200,
    location: 'B-06',
  },
  {
    id: 'P017',
    name: 'Axle Assembly',
    sku: 'AXLE-300',
    quantity: 56,
    category: 'Drivetrain',
    price: 1800,
    location: 'B-07',
  },
  {
    id: 'P018',
    name: 'Motor Mount',
    sku: 'MOT-MOUNT',
    quantity: 89,
    category: 'Drivetrain',
    price: 280,
    location: 'B-08',
  },
  {
    id: 'P019',
    name: 'Transmission Fluid',
    sku: 'TRANS-FLUID',
    quantity: 45,
    category: 'Drivetrain',
    price: 85,
    location: 'B-09',
  },
  {
    id: 'P020',
    name: 'Bearing Set',
    sku: 'BEARING-SET',
    quantity: 234,
    category: 'Drivetrain',
    price: 120,
    location: 'B-10',
  },

  // Electrical Systems (C section)
  {
    id: 'P021',
    name: 'Charging Port',
    sku: 'CHG-200',
    quantity: 156,
    category: 'Electrical',
    price: 450,
    location: 'C-01',
  },
  {
    id: 'P022',
    name: 'Wiring Harness',
    sku: 'WIRE-HARN',
    quantity: 78,
    category: 'Electrical',
    price: 680,
    location: 'C-02',
  },
  {
    id: 'P023',
    name: 'ECU Module',
    sku: 'ECU-001',
    quantity: 45,
    category: 'Electrical',
    price: 1500,
    location: 'C-03',
  },
  {
    id: 'P024',
    name: 'CAN Bus Cable',
    sku: 'CAN-CABLE',
    quantity: 234,
    category: 'Electrical',
    price: 45,
    location: 'C-04',
  },
  {
    id: 'P025',
    name: 'Relay Box',
    sku: 'RELAY-BOX',
    quantity: 67,
    category: 'Electrical',
    price: 320,
    location: 'C-05',
  },
  {
    id: 'P026',
    name: 'Circuit Breaker',
    sku: 'CIRC-BREAK',
    quantity: 89,
    category: 'Electrical',
    price: 180,
    location: 'C-06',
  },
  {
    id: 'P027',
    name: 'Connector Plug',
    sku: 'CONN-PLUG',
    quantity: 456,
    category: 'Electrical',
    price: 25,
    location: 'C-07',
  },
  {
    id: 'P028',
    name: 'Sensor Array',
    sku: 'SENSOR-ARR',
    quantity: 123,
    category: 'Electrical',
    price: 890,
    location: 'C-08',
  },
  {
    id: 'P029',
    name: 'LED Light Strip',
    sku: 'LED-STRIP',
    quantity: 189,
    category: 'Electrical',
    price: 65,
    location: 'C-09',
  },
  {
    id: 'P030',
    name: 'Fuse Set',
    sku: 'FUSE-SET',
    quantity: 345,
    category: 'Electrical',
    price: 35,
    location: 'C-10',
  },

  // Interior Components (D section)
  {
    id: 'P031',
    name: 'Display Console',
    sku: 'DSP-100',
    quantity: 78,
    category: 'Interior',
    price: 1200,
    location: 'D-01',
  },
  {
    id: 'P032',
    name: 'Touchscreen Panel',
    sku: 'TOUCH-PNL',
    quantity: 45,
    category: 'Interior',
    price: 890,
    location: 'D-02',
  },
  {
    id: 'P033',
    name: 'Seat Assembly',
    sku: 'SEAT-001',
    quantity: 34,
    category: 'Interior',
    price: 2800,
    location: 'D-03',
  },
  {
    id: 'P034',
    name: 'Door Panel',
    sku: 'DOOR-PNL',
    quantity: 67,
    category: 'Interior',
    price: 450,
    location: 'D-04',
  },
  {
    id: 'P035',
    name: 'Dashboard Cover',
    sku: 'DASH-COV',
    quantity: 23,
    category: 'Interior',
    price: 680,
    location: 'D-05',
  },
  {
    id: 'P036',
    name: 'Center Console',
    sku: 'CENTER-CON',
    quantity: 45,
    category: 'Interior',
    price: 1200,
    location: 'D-06',
  },
  {
    id: 'P037',
    name: 'Headliner',
    sku: 'HEADLINER',
    quantity: 28,
    category: 'Interior',
    price: 890,
    location: 'D-07',
  },
  {
    id: 'P038',
    name: 'Carpet Set',
    sku: 'CARPET-SET',
    quantity: 34,
    category: 'Interior',
    price: 450,
    location: 'D-08',
  },
  {
    id: 'P039',
    name: 'Sun Visor',
    sku: 'SUN-VISOR',
    quantity: 89,
    category: 'Interior',
    price: 120,
    location: 'D-09',
  },
  {
    id: 'P040',
    name: 'Grab Handle',
    sku: 'GRAB-HAND',
    quantity: 156,
    category: 'Interior',
    price: 85,
    location: 'D-10',
  },

  // Safety Systems (E section)
  {
    id: 'P041',
    name: 'Brake System',
    sku: 'BRK-400',
    quantity: 45,
    category: 'Safety',
    price: 2500,
    location: 'E-01',
  },
  {
    id: 'P042',
    name: 'Airbag Module',
    sku: 'AIRBAG-01',
    quantity: 67,
    category: 'Safety',
    price: 1800,
    location: 'E-02',
  },
  {
    id: 'P043',
    name: 'Seatbelt Assembly',
    sku: 'BELT-001',
    quantity: 123,
    category: 'Safety',
    price: 280,
    location: 'E-03',
  },
  {
    id: 'P044',
    name: 'ABS Sensor',
    sku: 'ABS-SENSOR',
    quantity: 89,
    category: 'Safety',
    price: 450,
    location: 'E-04',
  },
  {
    id: 'P045',
    name: 'Brake Pad Set',
    sku: 'PAD-SET',
    quantity: 234,
    category: 'Safety',
    price: 180,
    location: 'E-05',
  },
  {
    id: 'P046',
    name: 'Brake Disc',
    sku: 'DISC-001',
    quantity: 156,
    category: 'Safety',
    price: 320,
    location: 'E-06',
  },
  {
    id: 'P047',
    name: 'Brake Fluid',
    sku: 'BRK-FLUID',
    quantity: 78,
    category: 'Safety',
    price: 45,
    location: 'E-07',
  },
  {
    id: 'P048',
    name: 'Crash Sensor',
    sku: 'CRASH-SENS',
    quantity: 45,
    category: 'Safety',
    price: 890,
    location: 'E-08',
  },
  {
    id: 'P049',
    name: 'Emergency Kit',
    sku: 'EMERG-KIT',
    quantity: 23,
    category: 'Safety',
    price: 180,
    location: 'E-09',
  },
  {
    id: 'P050',
    name: 'Warning Triangle',
    sku: 'WARN-TRI',
    quantity: 34,
    category: 'Safety',
    price: 65,
    location: 'E-10',
  },

  // Wheels & Tires (F section)
  {
    id: 'P051',
    name: 'Tire Set',
    sku: 'TIR-800',
    quantity: 67,
    category: 'Wheels',
    price: 1800,
    location: 'F-01',
  },
  {
    id: 'P052',
    name: 'Alloy Wheel',
    sku: 'WHEEL-AL',
    quantity: 89,
    category: 'Wheels',
    price: 450,
    location: 'F-02',
  },
  {
    id: 'P053',
    name: 'Tire Pressure Sensor',
    sku: 'TPMS-001',
    quantity: 234,
    category: 'Wheels',
    price: 180,
    location: 'F-03',
  },
  {
    id: 'P054',
    name: 'Wheel Nut Set',
    sku: 'NUT-SET',
    quantity: 456,
    category: 'Wheels',
    price: 35,
    location: 'F-04',
  },
  {
    id: 'P055',
    name: 'Hub Cap',
    sku: 'HUB-CAP',
    quantity: 123,
    category: 'Wheels',
    price: 85,
    location: 'F-05',
  },
  {
    id: 'P056',
    name: 'Wheel Bearing',
    sku: 'WHEEL-BEAR',
    quantity: 156,
    category: 'Wheels',
    price: 280,
    location: 'F-06',
  },
  {
    id: 'P057',
    name: 'Valve Stem',
    sku: 'VALVE-STEM',
    quantity: 345,
    category: 'Wheels',
    price: 25,
    location: 'F-07',
  },
  {
    id: 'P058',
    name: 'Rim Strip',
    sku: 'RIM-STRIP',
    quantity: 189,
    category: 'Wheels',
    price: 45,
    location: 'F-08',
  },
  {
    id: 'P059',
    name: 'Tire Patch Kit',
    sku: 'PATCH-KIT',
    quantity: 78,
    category: 'Wheels',
    price: 65,
    location: 'F-09',
  },
  {
    id: 'P060',
    name: 'Wheel Spacer',
    sku: 'WHEEL-SPC',
    quantity: 67,
    category: 'Wheels',
    price: 120,
    location: 'F-10',
  },

  // Chassis & Suspension (G section)
  {
    id: 'P061',
    name: 'Suspension Kit',
    sku: 'SUS-600',
    quantity: 34,
    category: 'Chassis',
    price: 3200,
    location: 'G-01',
  },
  {
    id: 'P062',
    name: 'Shock Absorber',
    sku: 'SHOCK-001',
    quantity: 89,
    category: 'Chassis',
    price: 680,
    location: 'G-02',
  },
  {
    id: 'P063',
    name: 'Spring Assembly',
    sku: 'SPRING-ASM',
    quantity: 67,
    category: 'Chassis',
    price: 890,
    location: 'G-03',
  },
  {
    id: 'P064',
    name: 'Control Arm',
    sku: 'CTRL-ARM',
    quantity: 123,
    category: 'Chassis',
    price: 450,
    location: 'G-04',
  },
  {
    id: 'P065',
    name: 'Stabilizer Bar',
    sku: 'STAB-BAR',
    quantity: 56,
    category: 'Chassis',
    price: 280,
    location: 'G-05',
  },
  {
    id: 'P066',
    name: 'Bushing Set',
    sku: 'BUSH-SET',
    quantity: 234,
    category: 'Chassis',
    price: 85,
    location: 'G-06',
  },
  {
    id: 'P067',
    name: 'Ball Joint',
    sku: 'BALL-JOINT',
    quantity: 156,
    category: 'Chassis',
    price: 180,
    location: 'G-07',
  },
  {
    id: 'P068',
    name: 'Tie Rod End',
    sku: 'TIE-ROD',
    quantity: 89,
    category: 'Chassis',
    price: 120,
    location: 'G-08',
  },
  {
    id: 'P069',
    name: 'Sway Bar Link',
    sku: 'SWAY-LINK',
    quantity: 123,
    category: 'Chassis',
    price: 95,
    location: 'G-09',
  },
  {
    id: 'P070',
    name: 'Strut Mount',
    sku: 'STRUT-MNT',
    quantity: 67,
    category: 'Chassis',
    price: 150,
    location: 'G-10',
  },

  // Climate Control (H section)
  {
    id: 'P071',
    name: 'HVAC Unit',
    sku: 'HVC-300',
    quantity: 45,
    category: 'Climate',
    price: 1500,
    location: 'H-01',
  },
  {
    id: 'P072',
    name: 'AC Compressor',
    sku: 'AC-COMP',
    quantity: 34,
    category: 'Climate',
    price: 1200,
    location: 'H-02',
  },
  {
    id: 'P073',
    name: 'Evaporator Core',
    sku: 'EVAP-CORE',
    quantity: 56,
    category: 'Climate',
    price: 680,
    location: 'H-03',
  },
  {
    id: 'P074',
    name: 'Condenser Unit',
    sku: 'COND-UNIT',
    quantity: 45,
    category: 'Climate',
    price: 890,
    location: 'H-04',
  },
  {
    id: 'P075',
    name: 'Blower Motor',
    sku: 'BLOW-MOT',
    quantity: 78,
    category: 'Climate',
    price: 450,
    location: 'H-05',
  },
  {
    id: 'P076',
    name: 'Refrigerant',
    sku: 'REFR-134A',
    quantity: 123,
    category: 'Climate',
    price: 85,
    location: 'H-06',
  },
  {
    id: 'P077',
    name: 'HVAC Filter',
    sku: 'HVAC-FILT',
    quantity: 234,
    category: 'Climate',
    price: 45,
    location: 'H-07',
  },
  {
    id: 'P078',
    name: 'Temperature Sensor',
    sku: 'TEMP-SENS',
    quantity: 89,
    category: 'Climate',
    price: 120,
    location: 'H-08',
  },
  {
    id: 'P079',
    name: 'Vent Assembly',
    sku: 'VENT-ASM',
    quantity: 156,
    category: 'Climate',
    price: 180,
    location: 'H-09',
  },
  {
    id: 'P080',
    name: 'Duct Hose',
    sku: 'DUCT-HOSE',
    quantity: 189,
    category: 'Climate',
    price: 65,
    location: 'H-10',
  },

  // Additional Specialty Parts (I section)
  {
    id: 'P081',
    name: 'Solar Panel',
    sku: 'SOLAR-001',
    quantity: 23,
    category: 'Specialty',
    price: 2800,
    location: 'I-01',
  },
  {
    id: 'P082',
    name: 'GPS Module',
    sku: 'GPS-001',
    quantity: 67,
    category: 'Specialty',
    price: 680,
    location: 'I-02',
  },
  {
    id: 'P083',
    name: 'Camera Assembly',
    sku: 'CAM-ASM',
    quantity: 89,
    category: 'Specialty',
    price: 1200,
    location: 'I-03',
  },
  {
    id: 'P084',
    name: 'Radar Sensor',
    sku: 'RADAR-01',
    quantity: 45,
    category: 'Specialty',
    price: 1800,
    location: 'I-04',
  },
  {
    id: 'P085',
    name: 'Lidar Unit',
    sku: 'LIDAR-01',
    quantity: 12,
    category: 'Specialty',
    price: 4500,
    location: 'I-05',
  },
  {
    id: 'P086',
    name: 'Speaker System',
    sku: 'SPKR-SYS',
    quantity: 56,
    category: 'Specialty',
    price: 890,
    location: 'I-06',
  },
  {
    id: 'P087',
    name: 'Microphone Array',
    sku: 'MIC-ARRAY',
    quantity: 78,
    category: 'Specialty',
    price: 450,
    location: 'I-07',
  },
  {
    id: 'P088',
    name: 'WiFi Module',
    sku: 'WIFI-MOD',
    quantity: 123,
    category: 'Specialty',
    price: 280,
    location: 'I-08',
  },
  {
    id: 'P089',
    name: 'Bluetooth Chip',
    sku: 'BT-CHIP',
    quantity: 189,
    category: 'Specialty',
    price: 180,
    location: 'I-09',
  },
  {
    id: 'P090',
    name: 'Cellular Modem',
    sku: 'CELL-MOD',
    quantity: 67,
    category: 'Specialty',
    price: 650,
    location: 'I-10',
  },

  // Fasteners & Hardware (J section)
  {
    id: 'P091',
    name: 'Bolt Set M8',
    sku: 'BOLT-M8',
    quantity: 1234,
    category: 'Hardware',
    price: 25,
    location: 'J-01',
  },
  {
    id: 'P092',
    name: 'Nut Set M8',
    sku: 'NUT-M8',
    quantity: 1456,
    category: 'Hardware',
    price: 20,
    location: 'J-02',
  },
  {
    id: 'P093',
    name: 'Washer Set',
    sku: 'WASH-SET',
    quantity: 2345,
    category: 'Hardware',
    price: 15,
    location: 'J-03',
  },
  {
    id: 'P094',
    name: 'Screw Set',
    sku: 'SCRW-SET',
    quantity: 1890,
    category: 'Hardware',
    price: 30,
    location: 'J-04',
  },
  {
    id: 'P095',
    name: 'Rivet Kit',
    sku: 'RIVET-KIT',
    quantity: 567,
    category: 'Hardware',
    price: 85,
    location: 'J-05',
  },
  {
    id: 'P096',
    name: 'Clip Set',
    sku: 'CLIP-SET',
    quantity: 890,
    category: 'Hardware',
    price: 45,
    location: 'J-06',
  },
  {
    id: 'P097',
    name: 'Gasket Kit',
    sku: 'GASKET-KIT',
    quantity: 234,
    category: 'Hardware',
    price: 120,
    location: 'J-07',
  },
  {
    id: 'P098',
    name: 'O-Ring Set',
    sku: 'ORING-SET',
    quantity: 456,
    category: 'Hardware',
    price: 65,
    location: 'J-08',
  },
  {
    id: 'P099',
    name: 'Seal Kit',
    sku: 'SEAL-KIT',
    quantity: 123,
    category: 'Hardware',
    price: 180,
    location: 'J-09',
  },
  {
    id: 'P100',
    name: 'Grommet Set',
    sku: 'GROM-SET',
    quantity: 345,
    category: 'Hardware',
    price: 55,
    location: 'J-10',
  },
];

export const mockScanRecords: ScanRecord[] = [
  // Today's scans (should show up in "Scans Today")
  {
    id: 'S001',
    partId: 'P001',
    partName: 'Battery Pack',
    sku: 'BAT-5000',
    type: 'outgoing',
    quantity: 2,
    destination: 'New York Dealership',
    timestamp: new Date(), // Today
    scannedBy: 'John Warehouse',
  },
  {
    id: 'S002',
    partId: 'P021',
    partName: 'Charging Port',
    sku: 'CHG-200',
    type: 'incoming',
    quantity: 50,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    scannedBy: 'John Warehouse',
  },
  {
    id: 'S003',
    partId: 'P011',
    partName: 'Electric Motor',
    sku: 'MOT-3000',
    type: 'outgoing',
    quantity: 1,
    destination: 'Texas Dealership',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    scannedBy: 'John Warehouse',
  },
  {
    id: 'S004',
    partId: 'P031',
    partName: 'Display Console',
    sku: 'DSP-100',
    type: 'incoming',
    quantity: 25,
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
    scannedBy: 'John Warehouse',
  },
  {
    id: 'S005',
    partId: 'P041',
    partName: 'Brake System',
    sku: 'BRK-400',
    type: 'outgoing',
    quantity: 3,
    destination: 'Florida Dealership',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8 hours ago
    scannedBy: 'John Warehouse',
  },
  {
    id: 'S006',
    partId: 'P051',
    partName: 'Tire Set',
    sku: 'TIR-800',
    type: 'incoming',
    quantity: 15,
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000), // 10 hours ago
    scannedBy: 'John Warehouse',
  },
  {
    id: 'S007',
    partId: 'P061',
    partName: 'Suspension Kit',
    sku: 'SUS-600',
    type: 'outgoing',
    quantity: 2,
    destination: 'California Dealership',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12 hours ago
    scannedBy: 'John Warehouse',
  },

  // Previous days' scans
  {
    id: 'S008',
    partId: 'P002',
    partName: 'Battery Cell',
    sku: 'BAT-1000',
    type: 'incoming',
    quantity: 100,
    timestamp: new Date('2025-10-11T16:45:00'),
    scannedBy: 'John Warehouse',
  },
  {
    id: 'S009',
    partId: 'P012',
    partName: 'Motor Controller',
    sku: 'MOT-CTRL',
    type: 'outgoing',
    quantity: 5,
    destination: 'Illinois Dealership',
    timestamp: new Date('2025-10-11T14:20:00'),
    scannedBy: 'John Warehouse',
  },
  {
    id: 'S010',
    partId: 'P022',
    partName: 'Wiring Harness',
    sku: 'WIRE-HARN',
    type: 'incoming',
    quantity: 30,
    timestamp: new Date('2025-10-10T11:45:00'),
    scannedBy: 'John Warehouse',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'O001',
    parts: [
      {partId: 'P001', partName: 'Battery Pack', quantity: 1},
      {partId: 'P004', partName: 'Display Console', quantity: 2},
    ],
    requestedBy: 'Tom Mechanic',
    status: 'approved',
    createdAt: new Date(2025, 9, 8, 12, 0, 0),
    estimatedDelivery: new Date(2025, 9, 12, 12, 0, 0),
  },
  {
    id: 'O002',
    parts: [{partId: 'P002', partName: 'Electric Motor', quantity: 1}],
    requestedBy: 'Sarah Sales',
    status: 'pending',
    createdAt: new Date(2025, 9, 10, 12, 0, 0),
  },
];

export const mockSales: Sale[] = [
  // Current month sales (October 2025) - should show up in "Sales This Month"
  // Using Date constructor with year, month, day to avoid timezone issues
  // Note: month is 0-indexed (9 = October)
  {
    id: 'SL001',
    dealership: 'New York Dealership',
    model: 'E-Sedan Pro',
    price: 45000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 1, 12, 0, 0),
    customerName: 'Robert Johnson',
  },
  {
    id: 'SL002',
    dealership: 'New York Dealership',
    model: 'E-SUV Elite',
    price: 62000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 2, 12, 0, 0),
    customerName: 'Jennifer Smith',
  },
  {
    id: 'SL003',
    dealership: 'New York Dealership',
    model: 'E-Sedan Elite',
    price: 55000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 3, 12, 0, 0),
    customerName: 'Michael Chen',
  },
  {
    id: 'SL004',
    dealership: 'New York Dealership',
    model: 'E-SUV Pro',
    price: 58000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 4, 12, 0, 0),
    customerName: 'Amanda Rodriguez',
  },
  {
    id: 'SL005',
    dealership: 'New York Dealership',
    model: 'E-Sedan Pro',
    price: 45000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 5, 12, 0, 0),
    customerName: 'Kevin Thompson',
  },
  {
    id: 'SL006',
    dealership: 'New York Dealership',
    model: 'E-SUV Elite',
    price: 62000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 6, 12, 0, 0),
    customerName: 'Jessica Martinez',
  },
  {
    id: 'SL007',
    dealership: 'New York Dealership',
    model: 'E-Sedan Elite',
    price: 55000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 7, 12, 0, 0),
    customerName: 'Daniel Kim',
  },
  {
    id: 'SL008',
    dealership: 'New York Dealership',
    model: 'E-SUV Pro',
    price: 58000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 8, 12, 0, 0),
    customerName: 'Rachel Green',
  },
  {
    id: 'SL009',
    dealership: 'New York Dealership',
    model: 'E-Sedan Pro',
    price: 45000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 9, 12, 0, 0),
    customerName: 'David Wilson',
  },
  {
    id: 'SL010',
    dealership: 'New York Dealership',
    model: 'E-SUV Elite',
    price: 62000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 10, 12, 0, 0),
    customerName: 'Lisa Brown',
  },
  {
    id: 'SL011',
    dealership: 'New York Dealership',
    model: 'E-Sedan Elite',
    price: 55000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 11, 12, 0, 0),
    customerName: 'Mark Davis',
  },
  {
    id: 'SL012',
    dealership: 'New York Dealership',
    model: 'E-SUV Pro',
    price: 58000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 9, 12, 12, 0, 0),
    customerName: 'Susan Lee',
  },

  // Other dealerships sales
  {
    id: 'SL013',
    dealership: 'Texas Dealership',
    model: 'E-SUV Elite',
    price: 62000,
    salesPerson: 'Mike Sales',
    date: new Date(2025, 9, 9, 12, 0, 0),
    customerName: 'Carlos Rodriguez',
  },
  {
    id: 'SL014',
    dealership: 'Florida Dealership',
    model: 'E-Sedan Elite',
    price: 55000,
    salesPerson: 'Lisa Sales',
    date: new Date(2025, 9, 10, 12, 0, 0),
    customerName: 'Maria Garcia',
  },
  {
    id: 'SL015',
    dealership: 'California Dealership',
    model: 'E-SUV Pro',
    price: 58000,
    salesPerson: 'Alex Sales',
    date: new Date(2025, 9, 11, 12, 0, 0),
    customerName: 'James Wilson',
  },
  {
    id: 'SL016',
    dealership: 'Illinois Dealership',
    model: 'E-Sedan Pro',
    price: 45000,
    salesPerson: 'Tom Sales',
    date: new Date(2025, 9, 12, 12, 0, 0),
    customerName: 'Emily Johnson',
  },

  // Previous months (should not show in "This Month")
  {
    id: 'SL017',
    dealership: 'New York Dealership',
    model: 'E-Sedan Pro',
    price: 45000,
    salesPerson: 'Sarah Sales',
    date: new Date(2025, 8, 28, 12, 0, 0), // September 28
    customerName: 'Previous Month Sale',
  },
];

export const mockServiceTickets: ServiceTicket[] = [
  {
    id: 'T001',
    vehicleModel: 'E-Sedan Pro',
    customerName: 'David Wilson',
    issue: 'Charging port not working',
    status: 'in_progress',
    assignedMechanic: 'Tom Mechanic',
    createdAt: new Date(2025, 9, 9, 12, 0, 0),
  },
  {
    id: 'T002',
    vehicleModel: 'E-SUV Elite',
    customerName: 'Lisa Brown',
    issue: 'Battery range reduced',
    status: 'open',
    createdAt: new Date(2025, 9, 10, 12, 0, 0),
  },
  {
    id: 'T003',
    vehicleModel: 'E-Sedan Elite',
    customerName: 'Mark Davis',
    issue: 'Display screen flickering',
    status: 'open',
    createdAt: new Date(2025, 9, 11, 12, 0, 0),
  },
  {
    id: 'T004',
    vehicleModel: 'E-SUV Pro',
    customerName: 'Susan Lee',
    issue: 'Brake system warning light',
    status: 'in_progress',
    assignedMechanic: 'Tom Mechanic',
    createdAt: new Date(2025, 9, 11, 12, 0, 0),
  },
  {
    id: 'T005',
    vehicleModel: 'E-Sedan Pro',
    customerName: 'James Wilson',
    issue: 'Air conditioning not cooling',
    status: 'open',
    createdAt: new Date(2025, 9, 12, 12, 0, 0),
  },
  {
    id: 'T006',
    vehicleModel: 'E-SUV Elite',
    customerName: 'Maria Garcia',
    issue: 'Software update needed',
    status: 'completed',
    assignedMechanic: 'Tom Mechanic',
    createdAt: new Date(2025, 9, 8, 12, 0, 0),
    completedAt: new Date(2025, 9, 9, 12, 0, 0),
  },
  {
    id: 'T007',
    vehicleModel: 'E-Sedan Elite',
    customerName: 'Robert Taylor',
    issue: 'Tire pressure monitoring system error',
    status: 'completed',
    assignedMechanic: 'Tom Mechanic',
    createdAt: new Date(2025, 9, 7, 12, 0, 0),
    completedAt: new Date(2025, 9, 8, 12, 0, 0),
  },
  {
    id: 'T008',
    vehicleModel: 'E-SUV Pro',
    customerName: 'Jennifer Adams',
    issue: 'Navigation system not responding',
    status: 'open',
    createdAt: new Date(2025, 9, 12, 12, 0, 0),
  },
];

export const mockAnalytics: AnalyticsData = {
  totalSalesYTD: 12500000,
  totalSalesProjected: 18000000,
  totalPartsCostYTD: 2800000,
  totalPartsCostProjected: 4200000,
  dealerships: [
    {
      name: 'New York Dealership',
      location: 'New York, NY',
      salesYTD: 4200000,
      salesProjected: 6000000,
      partsCostYTD: 950000,
      partsCostProjected: 1400000,
    },
    {
      name: 'Texas Dealership',
      location: 'Austin, TX',
      salesYTD: 3800000,
      salesProjected: 5500000,
      partsCostYTD: 820000,
      partsCostProjected: 1200000,
    },
    {
      name: 'Florida Dealership',
      location: 'Miami, FL',
      salesYTD: 4500000,
      salesProjected: 6500000,
      partsCostYTD: 1030000,
      partsCostProjected: 1600000,
    },
  ],
  monthlySales: [
    {month: 'Jan', amount: 1200000},
    {month: 'Feb', amount: 1100000},
    {month: 'Mar', amount: 1350000},
    {month: 'Apr', amount: 1280000},
    {month: 'May', amount: 1450000},
    {month: 'Jun', amount: 1320000},
    {month: 'Jul', amount: 1400000},
    {month: 'Aug', amount: 1500000},
    {month: 'Sep', amount: 1600000},
    {month: 'Oct', amount: 500000},
  ],
};
